### ISSUE TITLE
Adding tags

### ISSUE THREAD

**Issue by liamcan** [Cannold/ghost#7]
We need to migrate some tags for Leslie's articles which are currently missing from the migrated data. At the moment these tags are more like categories on Leslie's [old site](https://old.cannold.com/). We would like them as tags in the new system. The tags should be as follows.

in-the-media -----------> In the media
research ---------------> Research
writings ----------------> Writings
events -----------------> Events

(The books category won't be necessary as it's being handled elsewhere)

In the backup data you can find the tags linked by the article `id` via the `taggable_id` on the tag object as per this example where it links to article 1068.

```yaml
--- !ruby/object:Tag
attributes:
  slug: in-the-media
  taggable_id: "1068"
  tag_phrase_id: "49"
  phrase: in-the-media
  position: "1"
  id: "1120"
  taggable_type: CanpubArticle
  site_id: "15"
```
